### ISSUE TITLE
Support gnome-42-2204-sdk for s390x and ppc64el architecture

### ISSUE THREAD

**Issue by SiboVG** [ubuntu/gnome-sdk#189]
Hi, I'm using the gnome extension to build my Java application, which works fine for `armhf` and `amd64`, but my application fails to build on `s390x` and `ppc64el` with the following error:
```
Failed to install or refresh snap 'gnome-42-2204-sdk'.
'gnome-42-2204-sdk' does not exist or is not available on channel 'latest/stable'.
Use `snap info gnome-42-2204-sdk` to get a list of channels the snap is available on.
```

What do you think I should do next? Is the gnome extension never going to work for those architectures?

Here's my `snapcraft.yml` file:
```YAML
name: openrocket
adopt-info: openrocket
grade: stable
summary: A free, fully featured model rocket simulator.
description: |
  OpenRocket is a free, fully featured model rocket simulator that allows you
  to design and simulate your rockets before actually building and flying them.

  The main features include

    * Six-degree-of-freedom flight simulation
    * Automatic design optimization
    * Realtime simulated altitude, velocity and acceleration display
    * Staging and clustering support
    * Cross-platform (Java-based)
    * Read more about it on the OpenRocket.info.
license: GPL-3.0
base: core22
confinement: strict

plugs:
  dot-java-user-prefs-openrocket:
    interface: personal-files
    read:
      - $HOME/.java/.userPrefs/OpenRocket
  dot-openrocket:
    interface: personal-files
    write:
      - $HOME/.openrocket

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
  - build-on: [armhf]
  - build-on: [ppc64el]
  - build-on: [s390x]

apps:
  openrocket:
    extensions: [gnome]
    command: bin/launcher
    plugs:
      - home
      - network
      - cups-control
      - opengl
      - dot-java-user-prefs-openrocket
      - dot-openrocket
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH"

parts:
  openrocket:
    plugin: ant
    build-packages:
      - ant
      - ant-contrib
      - ant-optional
      - openjdk-17-jdk
      - openjdk-17-jre
    source: .
    source-type: git
    ant-build-targets:
      - clean
      - check
      - unittest
      - jar
    override-pull: |
      # Override the pull in order to set the version and the grade.
      # In the future, the releases can be annotated tags and snapcraft
      # will use those for the version numbers.
      #
      # This can be extended to other parts of OpenRocket (to use the
      # git describe --tags command) but the build should be updated at
      # the same time so its consistent across all artifacts. Will defer
      # that to a later pull request.
      #
      # Until then, just use the build.version value
      craftctl default
      VERSION=$(cat core/resources/build.properties | awk -F'=' '/build\.version/ { print $2 }')
      craftctl set version="$VERSION"
    override-build: |
      craftctl default
      mv swing/build/jar/OpenRocket.jar $CRAFT_PART_INSTALL/OpenRocket.jar
    stage-packages:
      - openjdk-17-jdk
      - openjdk-17-jre
      - ca-certificates
      - ca-certificates-java
    prime:
      - -usr/lib/jvm/java-*/lib/security/cacerts
      - -usr/lib/jvm/java-*/jre/lib/security/cacerts
      - -usr/lib/jvm/java-*/lib/security/blacklisted.certs

  launcher:
    plugin: dump
    source: snap/local
    organize:
      'launcher': 'bin/'
```

Thanks for any help!
