### ISSUE TITLE
gnome-46-2404: libpixbufloader_svg.so: undefined symbol: rsvg_handle_get_pixbuf_and_error

### ISSUE THREAD

**Issue by knipknap** [ubuntu/gnome-sdk#279]
It seems that the libpixbufloader_svg.so has an incompatibility, leading to apps not showing icons:

```
$ snap run --shell rayforge
touch: cannot touch '/home/sam/snap/rayforge/common/.cache/desktop-runtime-date': No such file or directory
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/sam/snap/rayforge/common/.cache/gio-modules/libgiolibproxy.so
g_module_open() failed for /snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader_svg.so: /snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader_svg.so: undefined symbol: rsvg_handle_get_pixbuf_and_error
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

sam@desky:/home/sam/Documents/projects/code/rayforge$ echo $LD_LIBRARY_PATH 
/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/rayforge/x1/lib:/snap/rayforge/x1/usr/lib:/snap/rayforge/x1/usr/lib/x86_64-linux-gnu:/snap/rayforge/x1/usr/lib/x86_64-linux-gnu/blas:/snap/rayforge/x1/usr/lib/x86_64-linux-gnu/lapack:/snap/rayforge/x1/gpu-2404/usr/lib/x86_64-linux-gnu:/snap/rayforge/x1/gpu-2404/usr/lib/x86_64-linux-gnu/vdpau:/snap/rayforge/x1/gpu-2404/usr/lib/i386-linux-gnu:/snap/rayforge/x1/gpu-2404/usr/lib/i386-linux-gnu/vdpau:/var/lib/snapd/lib/gl/vdpau:/snap/rayforge/x1/gnome-platform/lib/x86_64-linux-gnu:/snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/rayforge/x1/gnome-platform/usr/lib:/snap/rayforge/x1/gnome-platform/lib:/snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libproxy

sam@desky:/home/sam/Documents/projects/code/rayforge$ ls /snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libproxy
libpxbackend-1.0.so
sam@desky:/home/sam/Documents/projects/code/rayforge$ 
```

Note the following: `libpixbufloader_svg.so: undefined symbol: rsvg_handle_get_pixbuf_and_error`

There are also two additional errors:
- `libpxbackend-1.0.so: cannot open shared object file: No such file or directory` - even though the library is there, and `LD_LIBRARY_PATH` has an entry that points to the directory containing it.
- When I then try to start my app within the snap: `/snap/rayforge/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/media/libmedia-gstreamer.so: undefined symbol: gdk_cicp_params_set_matrix_coefficients`

But I am guessing that those are different/unrelated problems.

Here is the snapcraft.yaml:

```yaml
name: rayforge
version: git
summary: A desktop application for laser cutting and engraving
description: |
  Rayforge is a desktop application designed for laser cutting
  and engraving. It provides an intuitive interface for users
  to create and manage their laser cutting projects.
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    command: bin/rayforge
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
      - x11
      - wayland
      - opengl
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/$ARCH/libproxy

slots:
  rayforge:
    interface: dbus
    bus: session
    name: com.barebaric.rayforge

parts:
  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-pip
      - python3-setuptools
      - git  # Required for git describe
    organize:
      data/com.barebaric.rayforge.desktop: share/applications/com.barebaric.rayforge.desktop
      data/com.barebaric.rayforge.metainfo.xml: share/metainfo/com.barebaric.rayforge.metainfo.xml
      data/com.barebaric.rayforge.svg: share/icons/hicolor/scalable/apps/com.barebaric.rayforge.svg
```
